runtime: python39
entrypoint: gunicorn -b :$PORT main:app
env_variables:
  CLOUD_SQL_PASSWORD: QmAQ+HI483Y61tSAQPgzE8vc
  DB_INSTANCE_NAME: db-instance
  DB_NAME: numbersdb
  DB_USER: rob
  PROJECT_NAME: random-numbers-assignment
  REGION: europe-west1

automatic_scaling:
  min_instances: 5
  max_instances: 15

handlers:
  - url: /static
    static_dir: static
  - url: /
    script: auto
