runtime: python39

env_variables:
  CLOUD_SQL_PASSWORD: "YFDH7aB9i0f6gNhkDaztTqjQ"
  DB_INSTANCE_NAME: "db-instance"
  DB_NAME: "random-numbers"
  DB_USER: "rob"
  PROJECT_NAME: "CIS3111-assignment"
  REGION: "europe-west1"

automatic_scaling:
  min_instances: 5
  max_instances: 15
