runtime: python
env: flex
entrypoint: python app.py

runtime_config:
  python_version: 3.7

automatic_scaling:
  min_num_instances: 5
  max_num_instances: 15
  cool_down_period_sec: 120

env_variables:
  REDIS_HOST: "10.252.125.115"
  REDIS_PORT: "6379"

service: api
