runtime: python310
entrypoint: python main.py
service: api
instance_class: F2

env_variables:
  CLOUD_SQL_CONNECTION_NAME: cis3111-2023-class:europe-west1:db-instance
  DB_USER: rob
  DB_PASSWORD: uWzKUp8YtnLuRqJP/dbeZLdV
  DB_NAME: numbersdb

automatic_scaling:
  min_instances: 5
  max_instances: 15
